// Visual identity design/src/app/components/PixelButton.tsx
import React from 'react';

interface PixelButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'accent' | 'success' | 'outline';
  size?: 'sm' | 'md' | 'lg';
  children: React.ReactNode;
}

export function PixelButton({ 
  variant = 'primary', 
  size = 'md', 
  children, 
  className = '',
  ...props 
}: PixelButtonProps) {
  const baseStyles = 'font-medium transition-all duration-200 active:translate-x-1 active:translate-y-1 active:shadow-none disabled:opacity-50 disabled:cursor-not-allowed border-[3px] border-black';
  
  const variantStyles = {
    primary: 'bg-primary text-primary-foreground hover:bg-primary-dark pixel-shadow',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary-dark pixel-shadow',
    accent: 'bg-accent text-accent-foreground hover:bg-accent-dark pixel-shadow',
    success: 'bg-success text-success-foreground hover:brightness-110 pixel-shadow',
    outline: 'bg-white text-foreground hover:bg-muted border-foreground pixel-shadow'
  };
  
  const sizeStyles = {
    sm: 'px-4 py-2 text-sm',
    md: 'px-6 py-3 text-base',
    lg: 'px-8 py-4 text-lg'
  };
  
  return (
    <button
      className={`${baseStyles} ${variantStyles[variant]} ${sizeStyles[size]} ${className}`}
      {...props}
    >
      {children}
    </button>
  );
}

// frontend/src/components/PixelButton.vue
<script setup>
defineProps({
  variant: {
    type: String,
    default: 'primary',
    validator: (v) => ['primary', 'secondary', 'accent', 'success', 'outline'].includes(v)
  },
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v)
  },
  disabled: Boolean
});
</script>

<template>
  <button
    :disabled="disabled"
    class="pixel-btn font-medium transition-all duration-200 active:translate-x-1 active:translate-y-1 active:shadow-none disabled:opacity-50 disabled:cursor-not-allowed border-[3px] border-black"
    :class="[
      {
        'bg-primary text-primary-foreground hover:bg-primary-dark pixel-shadow': variant === 'primary',
        'bg-secondary text-secondary-foreground hover:bg-secondary-dark pixel-shadow': variant === 'secondary',
        'bg-accent text-accent-foreground hover:bg-accent-dark pixel-shadow': variant === 'accent',
        'bg-success text-success-foreground hover:brightness-110 pixel-shadow': variant === 'success',
        'bg-white text-foreground hover:bg-muted border-foreground pixel-shadow': variant === 'outline'
      },
      {
        'px-4 py-2 text-sm': size === 'sm',
        'px-6 py-3 text-base': size === 'md',
        'px-8 py-4 text-lg': size === 'lg'
      }
    ]"
  >
    <slot />
  </button>
</template>
