// frontend/src/components/PixelCard.vue
<script setup>
defineProps({
  variant: {
    type: String,
    default: 'default',
    validator: (v) => ['default', 'primary', 'secondary', 'accent'].includes(v)
  }
});
</script>

<template>
  <div
    class="border-[3px] border-black pixel-shadow p-6"
    :class="{
      'bg-card border-border': variant === 'default',
      'bg-primary/10 border-primary': variant === 'primary',
      'bg-secondary/10 border-secondary': variant === 'secondary',
      'bg-accent/10 border-accent': variant === 'accent'
    }"
  >
    <slot />
  </div>
</template>

// Visual identity design/src/app/components/PixelCard.tsx
import React from 'react';

interface PixelCardProps {
  children: React.ReactNode;
  className?: string;
  variant?: 'default' | 'primary' | 'secondary' | 'accent';
}

export function PixelCard({ children, className = '', variant = 'default' }: PixelCardProps) {
  const variantStyles = {
    default: 'bg-card border-border',
    primary: 'bg-primary/10 border-primary',
    secondary: 'bg-secondary/10 border-secondary',
    accent: 'bg-accent/10 border-accent'
  };
  
  return (
    <div className={`border-[3px] border-black pixel-shadow p-6 ${variantStyles[variant]} ${className}`}>
      {children}
    </div>
  );
}
