// frontend/src/App.vue
<template>
  <main>
    <h1>🎮 Answr</h1>

    <div class="placeholder">
      <p>Quiz-Plattform in Entwicklung...</p>
      <p>Frontend-Komponenten kommen bald! (Vue 3)</p>
    </div>

    <!-- TODO: Vue-Routing und Views hinzufügen
      - Home/Landing Page
      - Moderator Dashboard
      - Quiz Creator
      - Game Lobby
      - Player View
      - Results/Leaderboard
    -->
  </main>
</template>

<script setup>
// TODO: Routing und globale State-Verwaltung (z.B. Pinia oder provide/inject)
</script>

<style scoped>
main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

h1 {
  color: #333;
  text-align: center;
}

.placeholder {
  text-align: center;
  margin-top: 3rem;
  color: #666;
}
</style>

// frontend/src/App.svelte
<script>
  // TODO: Routing implementieren
  let currentView = 'home';
</script>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  }

  main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
  }

  h1 {
    color: #333;
    text-align: center;
  }

  .placeholder {
    text-align: center;
    margin-top: 3rem;
    color: #666;
  }
</style>

<main>
  <h1>🎮 Answr</h1>
  
  <div class="placeholder">
    <p>Quiz-Plattform in Entwicklung...</p>
    <p>Frontend-Komponenten kommen bald!</p>
  </div>

  <!-- TODO: Komponenten hinzufügen
    - Home/Landing Page
    - Moderator Dashboard
    - Quiz Creator
    - Game Lobby
    - Player View
    - Results/Leaderboard
  -->
</main>
